# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Keep Coding
tagline:          'leandrocp'
description:      'Ruby, Rails, Emberjs. By <a href="https://twitter.com/leandrocesquini" target="_blank">@leandrocesquini</a>.'
url:              http://leandrocp.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Leandro Cesquini Pereira'
  url:            https://twitter.com/leandrocesquini

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/leandrocp/leandrocp.github.io
