title: Leandro Cesquini Pereira
description: Leandro Cesquini Pereira - Elixir & Phoenix
author: Leandro Cesquini Pereira
email: leandro@leandrocp.com.br
url: "http://leandrocp.com.br"
baseurl: ""
twitter_username: leandrocesquini
github_username: leandrocp

include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title/
sass:
  style: compressed
