title: Leandro Cesquini Pereira
description: A blog about Emberjs, Elixir, Ruby and some random things about software development. Written by Leandro Cesquini Pereira.
author: Leandro Cesquini Pereira
email: leandro.cesquini@gmail.com
url: http://leandrocp.github.io/
baseurl: "/"
twitter_username: leandrocesquini
github_username: leandrocp

include: [_pages]
markdown: kramdown
permalink: pretty
sass:
  style: compressed
